"""The words, orders and labels the app shows an EEG gallery in.

Served beside the manifest (``data/profile.json``, ``window.PROFILE``) so the
app hard-codes none of them. Moved verbatim from source-lightbox's app.js:

- ``acronyms``, ``metric_labels``, ``metric_order`` — display forms and the order
  of connectivity metrics;
- ``domains`` — the nav's domain order, and the domain promoted to its own
  heading (Sensor-level) with its sub-group (Source vs Sensor);
- ``analysis_order`` — analysis-name keywords, in reading order within a domain;
- ``inputs`` — the Localization section: its manifest key, route and words;
- ``categories`` — the frequency bands, in order;
- ``figures`` — filename tokens the app groups a module's figures by (kind,
  contrast, metric, band) and the two-level layouts (metric-first,
  measure-first);
- ``glossaries`` — the connectivity-metric definitions, on the analyses they
  apply to;
- ``table`` — how source-analytics' columns are grouped, labelled, hidden and
  formatted.

Group names are the study's own (its ``groups:``, in the manifest): the app
takes them from there, so nothing here names a study.
"""

VOCABULARY: dict = {'default_title': 'Source Analysis Gallery',
 'acronyms': {'psd': 'PSD',
              'pac': 'PAC',
              'mvpa': 'MVPA',
              'roi': 'ROI',
              'vertex': 'Vertex',
              'lmm': 'LMM',
              'itc': 'ITC',
              'ersp': 'ERSP',
              'stp': 'STP',
              'svm': 'SVM',
              'nbs': 'NBS',
              'assr': 'ASSR',
              'qc': 'QC',
              'eeg': 'EEG',
              'ica': 'ICA',
              'falff': 'fALFF',
              'fdr': 'FDR',
              'aic': 'AIC',
              'bic': 'BIC',
              'se': 'SE',
              'df': 'df',
              'aec': 'AEC',
              'pli': 'PLI',
              'wpli': 'wPLI',
              'dwpli': 'dwPLI',
              'dpli': 'dPLI',
              'aac': 'AAC',
              'ppc': 'PPC',
              'dtf': 'DTF',
              'te': 'TE',
              'cfc': 'CFC',
              'fcd': 'FCD',
              'auc': 'AUC',
              'tfce': 'TFCE',
              'fooof': 'FOOOF',
              'mi': 'MI'},
 'domains': {'order': ['Spectral',
                       'Connectivity',
                       'Directed',
                       'Cross-frequency',
                       'Multivariate',
                       'Sensor-level',
                       'Source vs Sensor',
                       'Evoked',
                       'Other'],
             'section': 'Sensor-level',
             'subsection': 'Source vs Sensor'},
 'analysis_order': ['psd',
                    'cluster',
                    'aperiodic',
                    'specparam',
                    'spatial',
                    'connectivity',
                    'cross_freq',
                    'directed',
                    'graph',
                    'nbs',
                    'comparison',
                    'mvpa',
                    'evoked'],
 'inputs': {'key': 'localization',
            'route': 'localization',
            'title': 'Localization',
            'lead': 'Source-reconstruction pipelines and per-subject QC.',
            'outlier_rule': 'z &gt; 2 on key metrics',
            'search_words': ['localization', 'qc']},
 'categories': {'order': ['Delta', 'Theta', 'Alpha', 'Beta', 'Low Gamma', 'High Gamma', 'Epsilon']},
 'figures': {'tokens': {'conn_metric': ['imag_coherence',
                                        'partial_correlation',
                                        'partial_corr',
                                        'coherence',
                                        'dwpli',
                                        'wpli',
                                        'dpli',
                                        'pli',
                                        'aec'],
                        'coupling_metric': ['pac', 'aac', 'ppc'],
                        'band': ['low_gamma',
                                 'high_gamma',
                                 'low gamma',
                                 'high gamma',
                                 'peak_alpha',
                                 'spectral_slope',
                                 'delta',
                                 'theta',
                                 'alpha',
                                 'beta',
                                 'gamma',
                                 'epsilon'],
                        'power': ['delta_ref', 'absolute', 'relative'],
                        'flow': ['inflow', 'outflow', 'netflow'],
                        'measure': ['summary', 'exponent', 'offset']},
             'kind_tokens': ['conn_metric', 'coupling_metric', 'band', 'power', 'flow', 'measure'],
             'axes': [{'tokens': 'conn_metric', 'label': 'metric'},
                      {'tokens': 'coupling_metric', 'label': 'metric'},
                      {'tokens': 'band', 'label': 'name'}],
             'nested': [{'tokens': ['conn_metric'],
                         'order': ['imag_coherence', 'dwpli', 'pli', 'aec', 'coherence'],
                         'labels': {'imag_coherence': 'Imag. coherence',
                                    'coherence': 'Coherence',
                                    'dwpli': 'dwPLI',
                                    'wpli': 'wPLI',
                                    'pli': 'PLI',
                                    'dpli': 'dPLI',
                                    'aec': 'AEC',
                                    'partial_corr': 'Partial corr.',
                                    'partial_correlation': 'Partial corr.',
                                    'pac': 'PAC',
                                    'aac': 'AAC',
                                    'ppc': 'PPC'}},
                        {'tokens': ['power', 'measure'],
                         'order': ['absolute', 'relative', 'delta_ref', 'exponent', 'offset'],
                         'labels': {'absolute': 'Absolute power',
                                    'relative': 'Relative power',
                                    'delta_ref': 'Delta-referenced power',
                                    'exponent': 'Aperiodic exponent',
                                    'offset': 'Aperiodic offset'}}]},
 'metric_order': ['imag_coherence', 'dwpli', 'pli', 'aec', 'coherence'],
 'metric_labels': {'imag_coherence': 'Imag. coherence',
                   'coherence': 'Coherence',
                   'dwpli': 'dwPLI',
                   'wpli': 'wPLI',
                   'pli': 'PLI',
                   'dpli': 'dPLI',
                   'aec': 'AEC',
                   'partial_corr': 'Partial corr.',
                   'partial_correlation': 'Partial corr.',
                   'pac': 'PAC',
                   'aac': 'AAC',
                   'ppc': 'PPC'},
 'glossaries': [{'title': 'Connectivity metric definitions',
                 'applies_to': '(_connectivity|_nbs|_graph|fcd_comparison)$',
                 'entries': [{'key': 'coherence',
                              'name': 'Coherence (magnitude-squared)',
                              'def': 'Squared cross-spectrum normalized by both auto-spectra, '
                                     '|S<sub>xy</sub>|²\u2009/\u2009'
                                     '(S<sub>xx</sub>·S<sub>yy</sub>); range 0–1. Total linear '
                                     'coupling at a frequency — but maximally sensitive to '
                                     'zero-lag volume conduction.',
                              'cite': 'Carter 1987; classical'},
                             {'key': 'imag_coherence',
                              'name': 'Imaginary coherence',
                              'def': 'Imaginary part of coherency, ℑ(S<sub>ij</sub>)\u2009/\u2009'
                                     '√(S<sub>ii</sub>·S<sub>jj</sub>). Volume-conduction coupling '
                                     'is purely real, so a non-zero imaginary part reflects '
                                     'genuine time-lagged interaction.',
                              'cite': 'Nolte et al. 2004'},
                             {'key': 'pli',
                              'name': 'Phase Lag Index (PLI)',
                              'def': 'Consistency of the sign of the phase difference, '
                                     '|⟨sign(ℑ)⟩|; range 0–1. Ignores zero-lag (volume-conduction) '
                                     'coupling by construction.',
                              'cite': 'Stam et al. 2007'},
                             {'key': 'wpli',
                              'name': 'Weighted PLI (wPLI)',
                              'def': 'PLI weighted by the magnitude of the imaginary '
                                     'cross-spectrum, |E{ℑ}|\u2009/\u2009E{|ℑ|}. Less sensitive to '
                                     'noise and to small perturbations near zero phase lag.',
                              'cite': 'Vinck et al. 2011, Eq. 8'},
                             {'key': 'dwpli',
                              'name': 'Debiased weighted PLI² (dwPLI)',
                              'def': 'wPLI² with the sample-size bias removed (self-term diagonal '
                                     'excluded). May take small negative values where true '
                                     'connectivity is ~0 — expected, not an error.',
                              'cite': 'Vinck et al. 2011, Eqs. 31–32'},
                             {'key': 'dpli',
                              'name': 'Directed PLI (dPLI)',
                              'def': 'Directional PLI: mean Heaviside of the phase difference; '
                                     'range 0–1. dPLI\u2009>\u20090.5 ⇒ region i phase-leads j; '
                                     'dPLI<sub>ij</sub>+dPLI<sub>ji</sub>=1.',
                              'cite': 'Stam & van Straaten 2012'},
                             {'key': 'aec',
                              'name': 'Orthogonalized amplitude-envelope correlation (AEC)',
                              'def': 'Pearson correlation of band-power envelopes after pairwise '
                                     'orthogonalization removes the zero-lag shared signal (both '
                                     'directions averaged). Captures amplitude co-modulation of '
                                     'genuinely distinct sources.',
                              'cite': 'Hipp et al. 2012'},
                             {'key': 'partial_corr',
                              'name': 'Partial correlation',
                              'def': 'Correlation between two regions with all others regressed '
                                     'out, from the (shrinkage-regularized) inverse covariance: '
                                     '−p<sub>ij</sub>\u2009/\u2009'
                                     '√(p<sub>ii</sub>·p<sub>jj</sub>). Separates direct from '
                                     'indirect connections.',
                              'cite': 'Marrelec et al. 2006'}]}],
 'table': {'primary_group': [{'column': 'hypothesis', 'label': 'Contrast', 'format': 'contrast'},
                             {'column': 'contrast', 'label': 'Contrast', 'format': 'contrast'},
                             {'column': 'key', 'label': 'Key', 'format': 'name'}],
           'group_candidates': [{'columns': ['measure_type', 'type', 'power_type'],
                                 'label': 'Measure Type',
                                 'format': 'measure'},
                                {'columns': ['dv', 'measure'],
                                 'label': 'Measure',
                                 'format': 'measure'},
                                {'columns': ['kind'], 'label': 'Test', 'format': 'name'},
                                {'columns': ['freq_pair'],
                                 'label': 'Frequency Pair',
                                 'format': 'name'},
                                {'columns': ['parameter'], 'label': 'Parameter', 'format': 'name'},
                                {'columns': ['band'], 'label': 'Band', 'format': 'name'},
                                {'columns': ['conn_metric'],
                                 'label': 'Connectivity',
                                 'format': 'name'},
                                {'columns': ['metric'], 'label': 'Metric', 'format': 'name'},
                                {'columns': ['graph_metric'],
                                 'label': 'Graph Metric',
                                 'format': 'name'}],
           'hidden_columns': ['converged',
                              'singular',
                              'convergence',
                              'aic_spatial',
                              'bic_spatial',
                              'aic_nonspatial',
                              'bic_nonspatial',
                              'aic_improvement',
                              'sig_label'],
           'header_labels': {'group_f': 'Group F',
                             'group_p': 'Group p',
                             'roi_f': 'ROI F',
                             'roi_p': 'ROI p',
                             'interaction_f': 'Interaction F',
                             'interaction_p': 'Interaction p',
                             'group_q': 'Group q (FDR)',
                             'group_significant': 'Group Sig.',
                             'interaction_q': 'Interaction q (FDR)',
                             'interaction_significant': 'Interact. Sig.',
                             'n_a': 'N (A)',
                             'n_b': 'N (B)',
                             'n_rois': 'N ROIs',
                             'n_regions': 'N Regions',
                             'group_a': 'Group A',
                             'group_b': 'Group B',
                             'measure_type': 'Type',
                             'dv': 'Measure',
                             't_ratio': 't',
                             't_value': 't',
                             'p_value': 'p',
                             'q_value': 'q (FDR)',
                             'hedges_g': "Hedges' g",
                             'hypothesis': 'Contrast',
                             'spatial': 'ROI / unit',
                             'stat': 'Statistic',
                             'effect_size': 'Effect size',
                             'effect_size_type': 'Effect type',
                             'estimate_lcl': 'Estimate (LCL)',
                             'estimate_ucl': 'Estimate (UCL)',
                             'std_error': 'SE',
                             'estimated_range_mm': 'Range (mm)',
                             'mean_t': 'Mean |t|',
                             'max_abs_t': 'Max |t|',
                             'mean_hedges_g': 'Mean |g|',
                             'max_abs_hedges_g': 'Max |g|',
                             'n_nominal_sig': 'N sig. (uncorr.)',
                             'n_vertices': 'N Vertices',
                             'cluster_stat': 'Cluster Stat',
                             'peak_t': 'Peak t',
                             'p_corrected': 'p (corrected)',
                             'cluster_id': 'Cluster',
                             'vertex_idx': 'Vertex',
                             'conn_metric': 'Connectivity',
                             'graph_metric': 'Graph Metric',
                             'p_fdr': 'p (FDR)',
                             'emmean_a': 'EMM (A)',
                             'emmean_b': 'EMM (B)',
                             'mean_a': 'Mean (A)',
                             'mean_b': 'Mean (B)',
                             'sd_a': 'SD (A)',
                             'sd_b': 'SD (B)',
                             't_stat': 't',
                             'observed_diff': 'Diff'},
           'cell_formats': {'contrast': 'contrast',
                            'hypothesis': 'contrast',
                            'group_a': 'group',
                            'group_b': 'group',
                            'group': 'group',
                            'measure': 'measure',
                            'dv': 'measure',
                            'measure_type': 'measure',
                            'band': 'name',
                            'metric': 'name',
                            'graph_metric': 'name',
                            'conn_metric': 'name',
                            'significant': 'flag',
                            'group_significant': 'flag',
                            'interaction_significant': 'flag'},
           'number_formats': [{'match': '^p$|^p_|_p$|p_value|p_corrected|q_value|group_q|interaction_q|p_fdr',
                               'format': 'p'},
                              {'match': '^f$|_f$|group_f|roi_f|interaction_f|^t$|^stat$|t_ratio|t_value|t_stat|peak_t|peak_stat|mean_stat|mean_t|max_abs_t|cluster_stat',
                               'format': 'fixed3'},
                              {'match': 'hedges_g|mean_hedges_g|max_abs_hedges_g|cohen|^effect_size$',
                               'format': 'fixed3'},
                              {'match': 'estimate|coefficient|std_error|^se$|emmean|^mean|^sd',
                               'format': 'fixed4'},
                              {'match': '^df$', 'format': 'df'},
                              {'match': '^aic|^bic', 'format': 'fixed1'},
                              {'match': '^n$|^n_|n_edges|n_vertices|n_rois|n_regions|n_nominal|n_sig|cluster_id|vertex_idx|n_permutations',
                               'format': 'count'}]}}
